# Generated by Django 4.2.2 on 2023-06-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_rent_tenant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rent',
            index=models.Index(fields=['expiration_date'], name='rent_rent_expirat_5a17cc_idx'),
        ),
    ]
