# Generated by Django 4.2.2 on 2023-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('vendor_code', models.CharField(max_length=6, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=6, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=60)),
                ('year', models.SmallIntegerField()),
                ('added', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('rented', models.IntegerField(default=0)),
                ('out_of_stock', models.BooleanField(default=False)),
            ],
        ),
    ]
