# Generated by Django 4.2.2 on 2023-06-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['vendor_code'], name='books_book_vendor__eed7d3_idx'),
        ),
    ]
